name: Deploy HTML using Github aciton Robot

# 1. When should the robot work?
on: 
  push:
    branches: [main]
# 2. What should the robot do?

jobs:
  build-and-test:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Check if file is exist
      run: |
        if [ -f index.html ]; then
          echo "Success file is exist"
        else:
          echo "Error! index.html file is not exit"
          exit 1
        fi
    
    
